### ISSUE TITLE
The bot does not work any more

### ISSUE THREAD

**Issue by nguyenanh29** [recitativonika/Dawn-Validator-bot#3]
🔍 Processing: ....using proxy: http://proxy1:port...
⚠️ Error during fetching the points: Request failed with status code 400
❌ No points available for .....
---

**Comment by recitativonika** [comment]
I tested and it still work, try again and check your account.js and config.js.
It should work if you put correctly

**Comment by iam8373** [comment]
remove https:// from your proxy it will work
