### ISSUE TITLE
1 account with multi proxies

### ISSUE THREAD

**Issue by bscongluanbui** [recitativonika/Dawn-Validator-bot#5]
Hi I want to run 1 accounts with multiple proxies. How to run that?

**Comment by recitativonika** [comment]
this only support 1 proxy for 1 account, need to change script logic to make 1 account multiple proxy.
But, why would you need that? you do not need many proxy for one account.

**Comment by bscongluanbui** [comment]
> this only support 1 proxy for 1 account, need to change script logic to make 1 account multiple proxy. But, why would you need that? you do not need many proxy for one account.

More proxy for more point. Do this right?

**Comment by recitativonika** [comment]
No, it doesn't work that way.
