### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by bscongluanbui** [recitativonika/Dawn-Validator-bot#8]
⚠️ Error during keep-alive request for ....: Request failed with status code 403
⚠️ Error during keep-alive request for ...: Request failed with status code 502
I got 2 error and account not add point

**Comment by bscongluanbui** [comment]
> let the script to run for some couple a minute, do the total point show up in the console? if yes, you can ignore the error

The total point didn't show up. IT's show 0 point in total

**Comment by recitativonika** [comment]
do you run with proxy or not?, it might be because connection error or your ip blocked by the server. Can you try change your network or use proxy/other proxy? and gett the token again? 

If you still have problem after doing this, let me know. I will check later
